/**
 * Dados Mockados para Desenvolvimento
 * Sistema de Gestão do Grupo de Jovens - Paróquia Santa Terezinha
 */

import {
  Member,
  Event,
  Transaction,
  DashboardStats,
  Activity,
  MemberStatus,
  SaturdayType,
  AttendanceStatus,
  TransactionType,
  TransactionCategory,
} from '../types';

// ============================================================================
// MEMBROS MOCKADOS
// ============================================================================

export const mockMembers: Member[] = [
  // Rapazes (Male)
  {
    id: '1',
    name: 'João Pedro Silva',
    email: 'joao.silva@email.com',
    phone: '(11) 98765-4321',
    birthDate: new Date('2004-03-15'),
    gender: 'male',
    joinDate: new Date('2023-01-10'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=12',
    createdAt: new Date('2023-01-10'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '3',
    name: 'Lucas Oliveira',
    email: 'lucas.oliveira@email.com',
    phone: '(11) 98765-4323',
    birthDate: new Date('2003-11-08'),
    gender: 'male',
    joinDate: new Date('2022-08-20'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=33',
    createdAt: new Date('2022-08-20'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '5',
    name: 'Gabriel Ferreira',
    email: 'gabriel.ferreira@email.com',
    phone: '(11) 98765-4325',
    birthDate: new Date('2005-01-18'),
    gender: 'male',
    joinDate: new Date('2023-01-15'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=15',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '7',
    name: 'Rafael Souza',
    email: 'rafael.souza@email.com',
    phone: '(11) 98765-4327',
    birthDate: new Date('2003-12-10'),
    gender: 'male',
    joinDate: new Date('2022-09-05'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=52',
    createdAt: new Date('2022-09-05'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '9',
    name: 'Pedro Henrique Lima',
    email: 'pedro.lima@email.com',
    phone: '(11) 98765-4329',
    birthDate: new Date('2004-06-28'),
    gender: 'male',
    joinDate: new Date('2023-04-10'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=68',
    createdAt: new Date('2023-04-10'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '11',
    name: 'Matheus Pereira',
    email: 'matheus.pereira@email.com',
    phone: '(11) 98765-4331',
    birthDate: new Date('2003-10-19'),
    gender: 'male',
    joinDate: new Date('2022-10-15'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=60',
    createdAt: new Date('2022-10-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '13',
    name: 'Felipe Araújo',
    email: 'felipe.araujo@email.com',
    phone: '(11) 98765-4333',
    birthDate: new Date('2005-11-12'),
    gender: 'male',
    joinDate: new Date('2023-02-15'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=51',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '15',
    name: 'Thiago Mendes',
    email: 'thiago.mendes@email.com',
    phone: '(11) 98765-4335',
    birthDate: new Date('2003-09-01'),
    gender: 'male',
    joinDate: new Date('2022-09-20'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=56',
    createdAt: new Date('2022-09-20'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '17',
    name: 'Bruno Dias',
    email: 'bruno.dias@email.com',
    phone: '(11) 98765-4337',
    birthDate: new Date('2004-07-15'),
    gender: 'male',
    joinDate: new Date('2023-01-30'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=70',
    createdAt: new Date('2023-01-30'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '19',
    name: 'Vinicius Costa',
    email: 'vinicius.costa@email.com',
    phone: '(11) 98765-4339',
    birthDate: new Date('2004-12-05'),
    gender: 'male',
    joinDate: new Date('2023-05-10'),
    status: MemberStatus.ACTIVE,
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '21',
    name: 'Rodrigo Alves',
    email: 'rodrigo.alves@email.com',
    phone: '(11) 98765-4341',
    birthDate: new Date('2005-02-28'),
    gender: 'male',
    joinDate: new Date('2023-06-15'),
    status: MemberStatus.ACTIVE,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '23',
    name: 'Gustavo Moreira',
    email: 'gustavo.moreira@email.com',
    phone: '(11) 98765-4343',
    birthDate: new Date('2004-08-20'),
    gender: 'male',
    joinDate: new Date('2022-11-20'),
    status: MemberStatus.INACTIVE,
    createdAt: new Date('2022-11-20'),
    updatedAt: new Date('2026-05-15'),
  },
  // Moças (Female)
  {
    id: '2',
    name: 'Maria Eduarda Santos',
    email: 'maria.santos@email.com',
    phone: '(11) 98765-4322',
    birthDate: new Date('2005-07-22'),
    gender: 'female',
    joinDate: new Date('2023-02-05'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=5',
    createdAt: new Date('2023-02-05'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '4',
    name: 'Ana Clara Costa',
    email: 'ana.costa@email.com',
    phone: '(11) 98765-4324',
    birthDate: new Date('2004-05-30'),
    gender: 'female',
    joinDate: new Date('2023-03-12'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=9',
    createdAt: new Date('2023-03-12'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '6',
    name: 'Beatriz Almeida',
    email: 'beatriz.almeida@email.com',
    phone: '(11) 98765-4326',
    birthDate: new Date('2004-09-25'),
    gender: 'female',
    joinDate: new Date('2022-11-08'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=10',
    createdAt: new Date('2022-11-08'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '8',
    name: 'Júlia Rodrigues',
    email: 'julia.rodrigues@email.com',
    phone: '(11) 98765-4328',
    birthDate: new Date('2005-04-14'),
    gender: 'female',
    joinDate: new Date('2023-02-20'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=20',
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '10',
    name: 'Isabela Martins',
    email: 'isabela.martins@email.com',
    phone: '(11) 98765-4330',
    birthDate: new Date('2005-08-03'),
    gender: 'female',
    joinDate: new Date('2023-01-25'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=23',
    createdAt: new Date('2023-01-25'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '12',
    name: 'Larissa Carvalho',
    email: 'larissa.carvalho@email.com',
    phone: '(11) 98765-4332',
    birthDate: new Date('2004-02-07'),
    gender: 'female',
    joinDate: new Date('2023-03-05'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=32',
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '14',
    name: 'Camila Ribeiro',
    email: 'camila.ribeiro@email.com',
    phone: '(11) 98765-4334',
    birthDate: new Date('2004-04-26'),
    gender: 'female',
    joinDate: new Date('2022-12-10'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=44',
    createdAt: new Date('2022-12-10'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '16',
    name: 'Fernanda Gomes',
    email: 'fernanda.gomes@email.com',
    phone: '(11) 98765-4336',
    birthDate: new Date('2005-03-20'),
    gender: 'female',
    joinDate: new Date('2023-04-05'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=47',
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '18',
    name: 'Amanda Barbosa',
    email: 'amanda.barbosa@email.com',
    phone: '(11) 98765-4338',
    birthDate: new Date('2005-05-09'),
    gender: 'female',
    joinDate: new Date('2023-03-18'),
    status: MemberStatus.ACTIVE,
    photoUrl: 'https://i.pravatar.cc/150?img=28',
    createdAt: new Date('2023-03-18'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '20',
    name: 'Carolina Nunes',
    email: 'carolina.nunes@email.com',
    phone: '(11) 98765-4340',
    birthDate: new Date('2004-10-18'),
    gender: 'female',
    joinDate: new Date('2023-04-20'),
    status: MemberStatus.ACTIVE,
    createdAt: new Date('2023-04-20'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '22',
    name: 'Letícia Freitas',
    email: 'leticia.freitas@email.com',
    phone: '(11) 98765-4342',
    birthDate: new Date('2005-06-12'),
    gender: 'female',
    joinDate: new Date('2023-07-08'),
    status: MemberStatus.ACTIVE,
    createdAt: new Date('2023-07-08'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '24',
    name: 'Mariana Silva',
    email: 'mariana.silva@email.com',
    phone: '(11) 98765-4344',
    birthDate: new Date('2004-01-25'),
    gender: 'female',
    joinDate: new Date('2022-10-05'),
    status: MemberStatus.INACTIVE,
    createdAt: new Date('2022-10-05'),
    updatedAt: new Date('2026-05-15'),
  },
];

// ============================================================================
// EVENTOS MOCKADOS
// ============================================================================

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Sábado de Oração',
    description: 'Encontro de oração e louvor com adoração ao Santíssimo',
    date: new Date('2026-05-02'),
    startTime: '18:00',
    endTime: '21:15',
    location: 'Salão Paroquial',
    saturdayType: SaturdayType.FIRST,
    isSpecialEvent: false,
    attendees: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    attendance: {
      '1': AttendanceStatus.PRESENT,
      '2': AttendanceStatus.PRESENT,
      '3': AttendanceStatus.PRESENT,
      '4': AttendanceStatus.PRESENT,
      '5': AttendanceStatus.PRESENT,
      '6': AttendanceStatus.PRESENT,
      '7': AttendanceStatus.PRESENT,
      '8': AttendanceStatus.PRESENT,
      '9': AttendanceStatus.PRESENT,
      '10': AttendanceStatus.PRESENT,
      '11': AttendanceStatus.PRESENT,
      '12': AttendanceStatus.PRESENT,
    },
    createdAt: new Date('2026-04-15'),
    updatedAt: new Date('2026-05-02'),
  },
  {
    id: '2',
    title: 'Evento Especial - Retiro Espiritual',
    description: 'Retiro de fim de semana na Chácara São Francisco',
    date: new Date('2026-05-09'),
    startTime: '08:00',
    endTime: '18:00',
    location: 'Chácara São Francisco',
    saturdayType: SaturdayType.SECOND,
    isSpecialEvent: true,
    attendees: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
    attendance: {
      '1': AttendanceStatus.PRESENT,
      '2': AttendanceStatus.PRESENT,
      '3': AttendanceStatus.PRESENT,
      '4': AttendanceStatus.PRESENT,
      '5': AttendanceStatus.PRESENT,
      '6': AttendanceStatus.PRESENT,
      '7': AttendanceStatus.PRESENT,
      '8': AttendanceStatus.PRESENT,
      '9': AttendanceStatus.PRESENT,
      '10': AttendanceStatus.PRESENT,
      '11': AttendanceStatus.PRESENT,
      '12': AttendanceStatus.PRESENT,
      '13': AttendanceStatus.PRESENT,
      '14': AttendanceStatus.PRESENT,
      '15': AttendanceStatus.PRESENT,
    },
    createdAt: new Date('2026-04-10'),
    updatedAt: new Date('2026-05-09'),
  },
  {
    id: '3',
    title: 'Formação I - Sacramentos',
    description: 'Estudo sobre os Sacramentos da Igreja',
    date: new Date('2026-05-16'),
    startTime: '18:00',
    endTime: '21:15',
    location: 'Salão Paroquial',
    saturdayType: SaturdayType.THIRD,
    isSpecialEvent: false,
    attendees: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    attendance: {
      '1': AttendanceStatus.PRESENT,
      '2': AttendanceStatus.PRESENT,
      '3': AttendanceStatus.PRESENT,
      '4': AttendanceStatus.PRESENT,
      '5': AttendanceStatus.PRESENT,
      '6': AttendanceStatus.PRESENT,
      '7': AttendanceStatus.PRESENT,
      '8': AttendanceStatus.PRESENT,
      '9': AttendanceStatus.PRESENT,
      '10': AttendanceStatus.PRESENT,
    },
    createdAt: new Date('2026-04-20'),
    updatedAt: new Date('2026-05-16'),
  },
  {
    id: '4',
    title: 'Formação II - Vocação e Missão',
    description: 'Reflexão sobre vocação e missão do jovem cristão',
    date: new Date('2026-05-23'),
    startTime: '18:00',
    endTime: '21:15',
    location: 'Salão Paroquial',
    saturdayType: SaturdayType.FOURTH,
    isSpecialEvent: false,
    attendees: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
    attendance: {
      '1': AttendanceStatus.PRESENT,
      '2': AttendanceStatus.PRESENT,
      '3': AttendanceStatus.PRESENT,
      '4': AttendanceStatus.PRESENT,
      '5': AttendanceStatus.PRESENT,
      '6': AttendanceStatus.PRESENT,
      '7': AttendanceStatus.PRESENT,
      '8': AttendanceStatus.PRESENT,
      '9': AttendanceStatus.PRESENT,
      '10': AttendanceStatus.PRESENT,
      '11': AttendanceStatus.PRESENT,
    },
    createdAt: new Date('2026-04-25'),
    updatedAt: new Date('2026-05-23'),
  },
  {
    id: '5',
    title: 'Sábado de Oração',
    description: 'Encontro de oração e louvor com adoração ao Santíssimo',
    date: new Date('2026-06-06'),
    startTime: '18:00',
    endTime: '21:15',
    location: 'Salão Paroquial',
    saturdayType: SaturdayType.FIRST,
    isSpecialEvent: false,
    attendees: [],
    attendance: {},
    createdAt: new Date('2026-05-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '6',
    title: 'Evento Especial - Festa Junina',
    description: 'Festa Junina beneficente do Grupo de Jovens',
    date: new Date('2026-06-13'),
    startTime: '18:00',
    endTime: '23:00',
    location: 'Pátio da Paróquia',
    saturdayType: SaturdayType.SECOND,
    isSpecialEvent: true,
    attendees: [],
    attendance: {},
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: '7',
    title: 'Formação I - Doutrina Social da Igreja',
    description: 'Estudo sobre a Doutrina Social da Igreja',
    date: new Date('2026-06-20'),
    startTime: '18:00',
    endTime: '21:15',
    location: 'Salão Paroquial',
    saturdayType: SaturdayType.THIRD,
    isSpecialEvent: false,
    attendees: [],
    attendance: {},
    createdAt: new Date('2026-05-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: '8',
    title: 'Formação II - Espiritualidade Jovem',
    description: 'Reflexão sobre espiritualidade na vida do jovem',
    date: new Date('2026-06-27'),
    startTime: '18:00',
    endTime: '21:15',
    location: 'Salão Paroquial',
    saturdayType: SaturdayType.FOURTH,
    isSpecialEvent: false,
    attendees: [],
    attendance: {},
    createdAt: new Date('2026-05-15'),
    updatedAt: new Date('2026-05-15'),
  },
];

// ============================================================================
// TRANSAÇÕES MOCKADAS
// ============================================================================

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: TransactionType.INCOME,
    category: TransactionCategory.DONATION,
    amount: 150.0,
    description: 'Doação para o caixa do grupo',
    date: new Date('2026-05-01'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-05-01'),
    updatedAt: new Date('2026-05-01'),
  },
  {
    id: '2',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.FOOD,
    amount: 85.5,
    description: 'Lanches para o encontro de oração',
    date: new Date('2026-05-02'),
    eventId: '1',
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-05-02'),
    updatedAt: new Date('2026-05-02'),
  },
  {
    id: '3',
    type: TransactionType.INCOME,
    category: TransactionCategory.EVENT,
    amount: 450.0,
    description: 'Arrecadação do retiro espiritual',
    date: new Date('2026-05-09'),
    eventId: '2',
    paymentMethod: 'Pix',
    createdAt: new Date('2026-05-09'),
    updatedAt: new Date('2026-05-09'),
  },
  {
    id: '4',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.TRANSPORT,
    amount: 200.0,
    description: 'Transporte para o retiro (ônibus)',
    date: new Date('2026-05-09'),
    eventId: '2',
    paymentMethod: 'Transferência',
    createdAt: new Date('2026-05-09'),
    updatedAt: new Date('2026-05-09'),
  },
  {
    id: '5',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.FOOD,
    amount: 180.0,
    description: 'Alimentação do retiro',
    date: new Date('2026-05-09'),
    eventId: '2',
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-05-09'),
    updatedAt: new Date('2026-05-09'),
  },
  {
    id: '6',
    type: TransactionType.INCOME,
    category: TransactionCategory.DONATION,
    amount: 100.0,
    description: 'Doação anônima',
    date: new Date('2026-05-10'),
    paymentMethod: 'Pix',
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: '7',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.MATERIAL,
    amount: 65.0,
    description: 'Material para dinâmicas (cartolinas, canetas, etc)',
    date: new Date('2026-05-12'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-05-12'),
    updatedAt: new Date('2026-05-12'),
  },
  {
    id: '8',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.FOOD,
    amount: 75.0,
    description: 'Lanches para formação sobre sacramentos',
    date: new Date('2026-05-16'),
    eventId: '3',
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-05-16'),
    updatedAt: new Date('2026-05-16'),
  },
  {
    id: '9',
    type: TransactionType.INCOME,
    category: TransactionCategory.DONATION,
    amount: 80.0,
    description: 'Doação de membro',
    date: new Date('2026-05-18'),
    memberId: '3',
    paymentMethod: 'Pix',
    createdAt: new Date('2026-05-18'),
    updatedAt: new Date('2026-05-18'),
  },
  {
    id: '10',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.OTHER,
    amount: 45.0,
    description: 'Impressão de apostilas',
    date: new Date('2026-05-20'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-05-20'),
    updatedAt: new Date('2026-05-20'),
  },
  {
    id: '11',
    type: TransactionType.INCOME,
    category: TransactionCategory.DONATION,
    amount: 200.0,
    description: 'Doação de benfeitores',
    date: new Date('2026-04-15'),
    paymentMethod: 'Pix',
    createdAt: new Date('2026-04-15'),
    updatedAt: new Date('2026-04-15'),
  },
  {
    id: '12',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.FOOD,
    amount: 95.0,
    description: 'Lanches para encontro de abril',
    date: new Date('2026-04-18'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-04-18'),
    updatedAt: new Date('2026-04-18'),
  },
  {
    id: '13',
    type: TransactionType.INCOME,
    category: TransactionCategory.EVENT,
    amount: 320.0,
    description: 'Arrecadação da Páscoa Jovem',
    date: new Date('2026-04-05'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-04-05'),
    updatedAt: new Date('2026-04-05'),
  },
  {
    id: '14',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.MATERIAL,
    amount: 120.0,
    description: 'Bíblias e materiais de estudo',
    date: new Date('2026-03-22'),
    paymentMethod: 'Transferência',
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-22'),
  },
  {
    id: '15',
    type: TransactionType.INCOME,
    category: TransactionCategory.DONATION,
    amount: 150.0,
    description: 'Doação anônima',
    date: new Date('2026-03-10'),
    paymentMethod: 'Pix',
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: '16',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.FOOD,
    amount: 88.5,
    description: 'Lanches para formação',
    date: new Date('2026-03-15'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: '17',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.TRANSPORT,
    amount: 150.0,
    description: 'Transporte para visita ao asilo',
    date: new Date('2026-02-28'),
    paymentMethod: 'Pix',
    createdAt: new Date('2026-02-28'),
    updatedAt: new Date('2026-02-28'),
  },
  {
    id: '18',
    type: TransactionType.INCOME,
    category: TransactionCategory.EVENT,
    amount: 280.0,
    description: 'Rifa beneficente',
    date: new Date('2026-02-20'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: '19',
    type: TransactionType.EXPENSE,
    category: TransactionCategory.OTHER,
    amount: 55.0,
    description: 'Material de limpeza para o salão',
    date: new Date('2026-02-10'),
    paymentMethod: 'Dinheiro',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: '20',
    type: TransactionType.INCOME,
    category: TransactionCategory.DONATION,
    amount: 100.0,
    description: 'Doação de membro',
    date: new Date('2026-01-25'),
    memberId: '5',
    paymentMethod: 'Pix',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-01-25'),
  },
];

// ============================================================================
// ATIVIDADES RECENTES MOCKADAS
// ============================================================================

export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'attendance',
    description: 'João Pedro Silva confirmou presença no próximo encontro',
    timestamp: new Date('2026-05-18T14:30:00'),
    icon: 'CheckCircle',
  },
  {
    id: '2',
    type: 'transaction',
    description: 'Nova doação de R$ 80,00 registrada',
    timestamp: new Date('2026-05-18T10:15:00'),
    icon: 'AttachMoney',
  },
  {
    id: '3',
    type: 'member',
    description: 'Amanda Barbosa atualizou suas informações',
    timestamp: new Date('2026-05-17T16:45:00'),
    icon: 'Person',
  },
  {
    id: '4',
    type: 'event',
    description: 'Novo evento criado: Festa Junina',
    timestamp: new Date('2026-05-15T09:20:00'),
    icon: 'Event',
  },
  {
    id: '5',
    type: 'transaction',
    description: 'Despesa de R$ 45,00 com impressão de apostilas',
    timestamp: new Date('2026-05-14T11:00:00'),
    icon: 'Receipt',
  },
];

// ============================================================================
// ESTATÍSTICAS DO DASHBOARD
// ============================================================================

export const mockStats: DashboardStats = {
  totalMembers: mockMembers.filter((m) => m.status === MemberStatus.ACTIVE).length,
  nextEvent: mockEvents.find((e) => e.date > new Date()) || null,
  balance: mockTransactions.reduce((acc, t) => {
    return t.type === TransactionType.INCOME ? acc + t.amount : acc - t.amount;
  }, 0),
  attendanceRate: 85.5, // Percentual calculado baseado nos eventos passados
};

// Made with Bob